fail_fast: true
default_language_version:
    python: python3.13
exclude: |
    (?x)(
        ^.*/migrations/.*\.py$|
        ^.venv/.*|
        ^node_modules/.*|
        ^static/vendor/.*|
        ^media/.*|
        .*\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$
    )
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: ["check", "--select", "I", "--fix"]
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
