default_language_version:
    python: python3.13
exclude: |
    (?x)(
        ^.*/migrations/.*\.py$|
        ^.venv/.*|
        ^node_modules/.*|
        ^static/vendor/.*|
        ^media/.*|
        .*\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$
    )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      # Linting
      - id: ruff-check
        types_or: [python, pyi]
        args: ["--fix"]

      # Formatting
      - id: ruff-format
        types_or: [python, pyi]
